[tool.poetry]
name = "auto-whapp"
version = "0.0.0"
description = ""
authors = ["Br <bramreinders97@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10.0"
requests = "^2.32.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

