name: S2

on:
  schedule:
    - cron: "13 17 15 12 *"
  workflow_dispatch:  # Allow manual triggering of the workflow

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Merge Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge 3 --merge
