name: Scheduled Merge

on:
  schedule:
    # Run at 01:00 AM UTC on December 21
    - cron: "0 1 21 12 *"

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Merge Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge 2 --merge
