name: Test next 30 days

on:
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  test-next-30-days:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Assuming the script uses requests

      # Step 4: Execute the test script with environment variables
      - name: Run Test Script
        env:
          CHAT_ID: ${{ secrets.TEST_CHAT_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          python -m tests.test_next_30_days
