name: Daily Telegram Bot Script

on:
  schedule:
    # Schedule the workflow to run daily at 16:00 UTC
    - cron: '0 15 * * *'
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  run-telegram-bot:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Assuming the script uses requests

      # Step 4: Set CHAT_ID based on trigger type
      - name: Set Chat ID
        id: set-chat-id
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "CHAT_ID=${{ secrets.TEST_CHAT_ID }}" >> $GITHUB_ENV
          else
            echo "CHAT_ID=${{ secrets.CHAT_ID }}" >> $GITHUB_ENV
          fi

      # Step 5: Execute the script
      - name: Run Telegram Bot Script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ env.CHAT_ID }}
        run: |
          python telegram.py
